version: "3.5"

# limits
# deploy.resources.limits.cpu 1.5
# deploy.resources.limits.memory 550MB 

services:
  api01: &api
    image: fabionaspolini/rinha-backend-2024-q1
    hostname: api01
    environment:
      - ConnectionStrings__Rinha=Server=db;Port=5432;Database=rinha;User Id=rinha;Password=rinha;
    ports:
      - "5201:9999"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "60MB"

  api02:
    <<: *api 
    hostname: api02
    ports:
      - "5202:9999"
 
  nginx:
    image: nginx:1.25.4-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
      - "5200:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  db:
    image: postgres:16.2-alpine3.19
    hostname: db
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    ports:
      - "5433:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    deploy:
      resources:
        limits:
          # Note que a soma de todos os limites dos serviços
          # aqui declarados é de 1.5 unidades de CPU e 550MB
          # de memória. A distribuição feita aqui é apenas
          # um exemplo – distribua como quiser.
          cpus: "0.7"
          memory: "370MB"

# O uso do modo `bridge` deve ser adequado à carga que será usada no teste.
# A edição anterior se beneficiou do modo host pois o volume de requisições
# era relativamente alto e a virtualização da rede se tornou um gargalo, mas
# este modo é mais complexo de ser configurado. Fique à vontade para usar o
# modo que quiser desde que não conflite com portas trivialmente usadas em um
# SO.
# networks:
#   default:
#     driver: bridge
#     name: rinha-nginx-2024q1
