@RinhaBackend_2024_q1_HostAddress = http://localhost:9999

GET {{RinhaBackend_2024_q1_HostAddress}}/clientes/1/extrato
Accept: application/json

###

POST {{RinhaBackend_2024_q1_HostAddress}}/clientes/1/transacoes
Content-Type: application/json
Accept: application/json

{
    "valor": 1,
    "tipo" : "c",
    "descricao" : "teste"
}

###

GET {{RinhaBackend_2024_q1_HostAddress}}/clientes/1/extrato
Accept: application/json
